version: '3'
services:

  web-app:
    image: node:18-alpine
    container_name: web-app
    command: [sh, -c, "yarn && yarn dev"]
    ports:
      - "3000:3000"
    working_dir: '/webapp'
    tty: true
    volumes:
      - './:/webapp/'
    environment:
      HOST: 0.0.0.0
      PORT: 3000