version: "3.5"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
#    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./ssl:/etc/nginx/ssl/
      - ./ssl:/etc/ssl/ssl2/
    depends_on:
      - web-app
  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    working_dir: /usr/local/go/src/main
    volumes:
      - ./backend:/usr/local/go/src/main
    ports:
      - "8000:5000"
    depends_on:
      - db
    entrypoint: go run main.go
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
  web-app:
    image: node:18-alpine
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: web-app
#    command: [sh, -c, "yarn && yarn dev"]
    ports:
      - "8001:80"
#    working_dir: /webapp
#    tty: true
#    volumes:
#      - ./frontend:/usr/src/nuxt-app
    environment:
      HOST: 0.0.0.0
      PORT: 80
    depends_on:
      - server