MODE: "debug"
#Port: 5000
#DbHost: db
DbUser: user
DbPwd: mysecretpassword
DbName: postgres

GoogleClientID:
GoogleSecretKey:

JWT_TOKEN_LIFE: 2592000
JWT_SECRET:

Port: 3001
DbHost: localhost

Host: "http://localhost:8001"